# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d92b4219f971a7ff7f5be50963b3028fcd9141d9bfe72774842b3bb0c3c0e50dfe7291f038e419cb4a19391837926943a1893f03d55a1460994018e5bede03

test:
  secret_key_base: 1f99abce5cde6fc4b7ce60c5c35e24a27f6002626c24716c9e19604c4c930a5cc002ac615935ded99ba364576e217c41106021d5074eb866c66492840c1f4a17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
